[package]
name = "znap-attribute-collection"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
proc-macro2 = "1.0.85"
quote = "1.0.36"
solana-sdk = "1.18.16"
syn = "2.0.66"
znap-syn = { path = "../../syn" }

[lib]
proc-macro = true