[package]
name = "my-actions"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
solana-sdk = "2.0.1"
serde = "1.0.203"
znap = { path = "../../../../znap" }
spl-associated-token-account = "4.0.0"
spl-token = "6.0.0"
reqwest = { version = "0.12.5", features = ["json"] }
