[package]
name = "znap-derive-action"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.85"
quote = "1.0.36"
syn = "2.0.66"
znap-syn = { path = "../../syn" }

[lib]
proc-macro = true