[package]
name = "action-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deluxe = "0.5.0"
proc-macro2 = "1.0.85"
quote = "1.0.36"
syn = "2.0.66"

[lib]
proc-macro = true
