[package]
name = "znap-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
base64 = "0.22.1"
serde = "1.0.203"
solana-sdk = "1.18.16"
znap-attribute-collection = { path = "./attribute/collection" }
znap-derive-action = { path = "./derive/action" }
